full_rebuild: true
name: Getting Started
author: Wakanda SAS
url: http://wakanda.io
version: 0.1
repository: https://github.com/ssalibi/wakanda-studio
branch: gh-pages
encoding: utf-8
themes:
    general: wakanda
    code: github
version: 1.4
sass:
  sass_dir: ./_scss_partials
encoding: utf-8
defaults:
  -
    values:
      layout: "default"
exclude: [
.git,
.gitignore,
README.md,
LICENSE
]
